// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 9.1.0
// Project name: SquareLine_Project

#include "ui.h"
#include <Arduino.h>
void button_led_on(lv_event_t* e) {
	digitalWrite(4, HIGH);
}

void button_led_off(lv_event_t* e) {
	digitalWrite(4, LOW);
}
