// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 9.1.0
// Project name: SquareLine_Project

#include "ui.h"

lv_obj_t * ui_Screen1 = NULL;
lv_obj_t * ui_buttonon = NULL;
lv_obj_t * ui_onbutton = NULL;
lv_obj_t * ui_Button2 = NULL;
lv_obj_t * ui_offbutton = NULL;
// event funtions
void ui_event_buttonon(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        button_led_on(e);
    }
}

void ui_event_Button2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        button_led_off(e);
    }
}

// build funtions

void ui_Screen1_screen_init(void)
{
    ui_Screen1 = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_Screen1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_buttonon = lv_button_create(ui_Screen1);
    lv_obj_set_width(ui_buttonon, 100);
    lv_obj_set_height(ui_buttonon, 50);
    lv_obj_set_x(ui_buttonon, -8);
    lv_obj_set_y(ui_buttonon, -58);
    lv_obj_set_align(ui_buttonon, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_buttonon, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_buttonon, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_onbutton = lv_label_create(ui_buttonon);
    lv_obj_set_width(ui_onbutton, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_onbutton, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_onbutton, LV_ALIGN_CENTER);
    lv_label_set_text(ui_onbutton, "On");

    ui_Button2 = lv_button_create(ui_Screen1);
    lv_obj_set_width(ui_Button2, 100);
    lv_obj_set_height(ui_Button2, 50);
    lv_obj_set_x(ui_Button2, -6);
    lv_obj_set_y(ui_Button2, 32);
    lv_obj_set_align(ui_Button2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button2, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_Button2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_offbutton = lv_label_create(ui_Button2);
    lv_obj_set_width(ui_offbutton, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_offbutton, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_offbutton, LV_ALIGN_CENTER);
    lv_label_set_text(ui_offbutton, "Off");

    lv_obj_add_event_cb(ui_buttonon, ui_event_buttonon, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Button2, ui_event_Button2, LV_EVENT_ALL, NULL);

}

void ui_Screen1_screen_destroy(void)
{
    if(ui_Screen1) lv_obj_del(ui_Screen1);

    // NULL screen variables
    ui_Screen1 = NULL;
    ui_buttonon = NULL;
    ui_onbutton = NULL;
    ui_Button2 = NULL;
    ui_offbutton = NULL;

}
